### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by AvrumFeldman** [jim-dale/BankingTools#1]
Hi,

I'm no developer. I stumbled upon this work when trying to create QBO* files using PowerShell. From my research I was able to find out that technically QBO files are OFX files.

I know how to create .NET objects in PowerShell so I figure I should be able to use your work in PowerShell as well. I started playing around an creating object, but I'm stumbling around blindly on how to actually convert the object into a file.

Would it be possible to provide an example how to actually create an OFX file? I don't mind if the sample is in whichever language you want. I will do my best to try to figure it out.

```
$doc = [OfxNet.SgmlDocument]::new()
$doc.Header = [OfxNet.SgmlHeader]::new()
$doc.Root = [OfxNet.SgmlElement]::new("test","whatever")
```

 .* QBO files is QuickBooks implementation of OFX.

**Comment by jim-dale** [comment]
I don't have any plans to add support for writing OFX files. This project is only intended for parsing (reading) OFX documents, not writing.

A longer answer is that modern OFX files are pure XML files and it is therefore usually simpler to generate these directly from your own model classes using the built-in .NET framework XML functionality. Using either [System.Xml.XmlDocument](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmldocument) or LINQ to XML ([System.Xml.Linq.XDocument](https://docs.microsoft.com/en-us/dotnet/api/system.xml.linq.xdocument)).

For older style SGML documents, maybe search for other libraries on GitHub that support writing OFX files or just write the text out to a file yourself.
