### ISSUE TITLE
Trying to use .Net 8 on Windows with OfxNet - says it is only built for AMD64  

### ISSUE THREAD

**Issue by MarkAlanJones** [jim-dale/BankingTools#14]
_`warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\MarkA\.nuget\packages\ofxnet\1.4.0\lib\net8.0\OfxNet.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.`_

Is this AOT compiled ? shouldn't a package have AMD and Intel and MISL if it is AOT ? 

First .net 8 project

**Comment by jim-dale** [comment]
Hi Mark, it is not AOT it is just the target processor architecture. I have reverted the change anyway to give users a bit more flexibility, in particular for ARM processor support, so it should work. If you are on Windows I would suggest always building for 64 bit architecture as 32 bit Windows is no longer released.
