### ISSUE TITLE
Regex with $ precludes parsing documents that don't END with the value, but include the next tag

### ISSUE THREAD

**Issue by MarkAlanJones** [jim-dale/BankingTools#16]
My OFX files from my bank have lines like this

`<BANKMSGSRSV1><STMTTRNRS><TRNUID>20231219105650<STATUS><CODE>0<SEVERITY>INFO<MESSAGE>OK</STATUS>`

it contains partial tags, without an endline between them instead of appearing on separate lines
```
<CODE>0
<SEVERITY>INFO
<MESSAGE>OK
```

this will cause it to mis-parse and get confused several lines later, causing parsing errors that are hard to fix without stepping through code

e.g.
`Closing tag 'BANKTRANLIST' does not match opening tag '', line 21.`

when there is an opening tag.

I think this line of code with the $ is causing the issue:

`public static readonly Regex ValuePartialTagRegex = new Regex("^\\s*<([\\w\\.]+)>(.+)$", RegexOptions.IgnoreCase);`

However the bigger fix, is maybe ignoring the end line (strip them all off or reparse to replace < with crlf < ?
and keep track of the tag with a stack so you can have nested ones, instead of start and end on the same line ?

**Comment by jim-dale** [comment]
I will not have time to fix this issue. I suggest you fork the repo and fix it and then optionally create a pull request with the changes
